export const copy = {
  app: {
    name: 'API Pilot',
    tagline: 'Test LLM APIs fast',
    description:
      'Make one LLM call, inspect the raw JSON, and try the next model without leaving your browser.',
  },
  defaults: {
    systemPrompt: 'You are a helpful assistant.',
    firstMessage: 'Hello, what can you do?',
  },
  header: {
    themeLight: 'Light mode',
    themeDark: 'Dark mode',
    send: 'Send',
    sending: 'Sending...',
  },
  sections: {
    requestBuilder: 'Request builder',
    modelBrowser: 'Model browser',
    messages: 'Messages',
    templates: 'Templates',
    responseViewer: 'Response viewer',
    history: 'History',
  },
  labels: {
    rawJson: 'Raw JSON',
    provider: 'Provider',
    apiKey: 'API key',
    model: 'Model',
    baseUrl: 'Base URL',
    systemPrompt: 'System prompt',
    temperature: 'Temperature',
    maxTokens: 'Max tokens',
    topP: 'Top p',
    stream: 'Stream',
    status: 'Status',
    ttft: 'TTFT',
    total: 'Total',
    cost: 'Cost',
    tokens: 'Tokens',
    input: 'In',
    output: 'Out',
    totalShort: 'Total',
    selectedModel: 'Selected model',
    statusHeaders: 'Status code + headers',
  },
  actions: {
    copyCurl: 'Copy as cURL',
    copyText: 'Copy text',
    refresh: 'Refresh',
    addMessage: 'Add message',
    clear: 'Clear',
    replay: 'Replay',
    delete: 'Delete',
    remove: 'Remove',
    moveUp: 'Up',
    moveDown: 'Down',
  },
  roles: {
    system: 'system',
    user: 'user',
    assistant: 'assistant',
    tool: 'tool',
  },
  placeholders: {
    apiKey: 'Saved in this browser only',
    model: 'Pick a model or paste an ID',
    baseUrl: 'Use this for Ollama, LM Studio, or vLLM',
    systemPrompt: 'Set the behavior once. Leave it blank if you do not need it.',
    modelSearch: 'Search models, providers, or IDs',
    message: 'Write the next message',
    toolName: 'Tool name',
  },
  emptyStates: {
    response: 'Your next reply shows up here. Try a template or send a quick prompt.',
    history: 'No runs yet. Send one request and replay it from here.',
    selectedModel: 'Pick a model to see context, pricing, and capability hints.',
    selectedModelMissing: 'This model is not in the OpenRouter index yet.',
  },
  tooltips: {
    themeToggle: 'Switch the app theme',
    send: 'Send the current request',
    rawRequest: 'Show the exact JSON body that will be sent',
    rawResponse: 'Show the exact JSON returned by the provider',
    copyCurl: 'Copy a ready-to-run cURL command',
    copyText: 'Copy the extracted text response',
    refreshModels: 'Refresh the OpenRouter model index',
    addMessage: 'Add another message to the thread',
    moveUp: 'Move this message up',
    moveDown: 'Move this message down',
    removeMessage: 'Remove this message',
    clearHistory: 'Clear saved runs from this browser',
    replayHistory: 'Load this run back into the builder',
    deleteHistory: 'Delete this saved run',
    stream: 'Stream tokens as they arrive',
  },
  states: {
    loadingModels: 'Loading models...',
    modelsReady: 'Models ready',
    copiedCurl: 'cURL copied',
    copiedText: 'Text copied',
  },
  errors: {
    modelRequired: 'Add a model ID before you send the request.',
    loadModels: 'Could not load models. Refresh to try again.',
    sendFailed:
      'The request stopped before a response came back. Check the endpoint, API key, and browser CORS settings.',
    unsupportedProvider: 'This provider is not supported yet.',
    anthropicMaxTokens: 'Anthropic expects `max_tokens` at the top level of the request body.',
    openAiKey: 'OpenAI-style APIs expect `Authorization: Bearer <key>`.',
    geminiKey: 'Gemini expects `x-goog-api-key` and the model name in the URL.',
    customCors: 'The custom endpoint may be blocking CORS. Check the base URL and make sure the server is up.',
  },
  history: {
    errorStatus: 'error',
  },
  templatesIntro: {
    title: 'Start points',
    description: 'Each template fills the request so you can send it right away.',
  },
} as const;

export const providerCopy = {
  'openai-chat': 'OpenAI chat',
  'openai-responses': 'OpenAI responses',
  anthropic: 'Anthropic',
  gemini: 'Gemini',
  custom: 'Custom endpoint',
} as const;
